// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB53JqNKwf-6O_UUKDNND_37-qeHx8qWAo',
    appId: '1:803524973592:web:d8b1fefc7e6b58d6071f6d',
    messagingSenderId: '803524973592',
    projectId: 'vidbuy-1b7b9',
    authDomain: 'vidbuy-1b7b9.firebaseapp.com',
    storageBucket: 'vidbuy-1b7b9.firebasestorage.app',
    measurementId: 'G-6LBFCRX0ED',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6hgJT3rKJ9Si25Cl8XW0GYhN0vO3ddHU',
    appId: '1:803524973592:android:5c74db5bf626f231071f6d',
    messagingSenderId: '803524973592',
    projectId: 'vidbuy-1b7b9',
    storageBucket: 'vidbuy-1b7b9.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3lgISi6BZg4H_zMZ8u-dMwTb0D3T2sDE',
    appId: '1:803524973592:ios:67bf6fea7d38c69b071f6d',
    messagingSenderId: '803524973592',
    projectId: 'vidbuy-1b7b9',
    storageBucket: 'vidbuy-1b7b9.firebasestorage.app',
    iosBundleId: 'com.example.vidbuyApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB3lgISi6BZg4H_zMZ8u-dMwTb0D3T2sDE',
    appId: '1:803524973592:ios:67bf6fea7d38c69b071f6d',
    messagingSenderId: '803524973592',
    projectId: 'vidbuy-1b7b9',
    storageBucket: 'vidbuy-1b7b9.firebasestorage.app',
    iosBundleId: 'com.example.vidbuyApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB53JqNKwf-6O_UUKDNND_37-qeHx8qWAo',
    appId: '1:803524973592:web:181a9bd4fc9120c9071f6d',
    messagingSenderId: '803524973592',
    projectId: 'vidbuy-1b7b9',
    authDomain: 'vidbuy-1b7b9.firebaseapp.com',
    storageBucket: 'vidbuy-1b7b9.firebasestorage.app',
    measurementId: 'G-GTHKKTSGEX',
  );
}
